Repository vmware/powershell-module-for-vmware-cloud-foundation-reporting, pull requests merged in 2022-12, with the labels that each got.

#33 feat(overview): add esxi hosts
  VMware.CloudFoundation.Reporting.psm1
Labels: enhancement, report/overview

#35 chore(deps): bump dependencies
  VMware.CloudFoundation.Reporting.psm1
Labels: chore, dependencies

#46 feat(overview): add cluster host count
  VMware.CloudFoundation.Reporting.psm1
Labels: enhancement, report/overview

#47 docs: update `README.md`
  README.md
Labels: documentation

#48 docs: update `README.md`
  README.md
Labels: documentation

#49 chore(release): bump module metadata
  VMware.CloudFoundation.Reporting.psd1
Labels: chore, needs-review

#50 docs(release): update `README.md`
  README.md
Labels: documentation

#51 docs(release): update `CHANGELOG.md`
  CHANGELOG.md
Labels: documentation

#53 feat: add password policy functions
  CHANGELOG.md
  VMware.CloudFoundation.Reporting.psd1
  VMware.CloudFoundation.Reporting.psm1
Labels: enhancement, size/m, report/password

#55 feat: transfer `Publish-EsxiPasswordPolicy` to PowerValidatedSolutions
  VMware.CloudFoundation.Reporting.psm1
Labels: enhancement, size/xs

#57 docs: update `README.md`
  README.md
Labels: documentation

#59 fix: error in variable passed to Publish-NsxtHealth
  VMware.CloudFoundation.Reporting.psm1
Labels: bug, size/xs, report/health

#60 feat: improve code efficiency of Invoke-VcfHealthReport
  VMware.CloudFoundation.Reporting.psm1
Labels: enhancement, size/m, report/health

#61 feat: improve code efficiency of Invoke-VcfAlertReport
  VMware.CloudFoundation.Reporting.psm1
Labels: enhancement, size/s, report/alert

#62 feat: improve code efficiency of `Invoke-VcfConfigReport`
  VMware.CloudFoundation.Reporting.psm1
Labels: enhancement, size/s, report/config

#63 feat: improve code efficiency of `Invoke-VcfPasswordPolicy`
  VMware.CloudFoundation.Reporting.psd1
  VMware.CloudFoundation.Reporting.psm1
Labels: enhancement, size/s, report/password

#64 feat: code efficiency for Publish-StorageCapacityHealth
  VMware.CloudFoundation.Reporting.psm1
Labels: enhancement, size/s
