Repository vmware/powershell-module-for-vmware-cloud-foundation-reporting, pull requests merged in 2022-11, with the labels that each got.

#19 docs: update `README.md`
  README.md
Labels: documentation

#21 feat: enhancements to Test-VcfReportingPrereq
  VMware.CloudFoundation.Reporting.psm1
Labels: enhancement, size/s

#24 fix: remove invoke prerequisites check
  README.md
  VMware.CloudFoundation.Reporting.psm1
Labels: bug

#27 fix: update prerequisites version check
  VMware.CloudFoundation.Reporting.psm1
Labels: bug

#25 fix: nsx one-to-many
  VMware.CloudFoundation.Reporting.psm1
Labels: bug

#30 chore(gh): update bug report template
  .github/ISSUE_TEMPLATE/bug.yml
Labels: chore

#31 feat: Add vRealize Suite Support for Request-LocalUserExpiry
  VMware.CloudFoundation.Reporting.psm1
Labels: enhancement, size/xs
