Repository vmware/powershell-module-for-vmware-cloud-foundation-reporting, pull requests merged in 2023-11, with the labels that each got.

#185 docs: add air-gapped install
  docs/install.md
  docs/snippets/copy-module-local-linux.sh
  docs/snippets/copy-module-local-windows.ps1
  docs/snippets/import-module-local-linux.ps1
  docs/snippets/pre-req-linux.sh
  docs/snippets/save-module-local-linux.ps1
  docs/snippets/save-module-local-windows.ps1
Labels: documentation

#189 docs: update install module with repository flag
  docs/snippets/install-module.ps1
  docs/snippets/save-module-local-linux.ps1
  docs/snippets/save-module-local-windows.ps1
Labels: dependencies

#191 feat: add check for cmdlet prerequisites
  CHANGELOG.md
  VMware.CloudFoundation.Reporting.psd1
  VMware.CloudFoundation.Reporting.psm1
Labels: enhancement

#193 chore: update copyright
  LICENSE
  Makefile
  NOTICE
  README.md
  VMware.CloudFoundation.Reporting.psd1
  VMware.CloudFoundation.Reporting.psm1
  docs/index.md
  mkdocs.yml
Labels: chore
