Repository vmware/powershell-module-for-vmware-cloud-foundation-reporting, pull requests merged in 2023-01, with the labels that each got.

#65 fix(overview): exclude hcx hosts
  VMware.CloudFoundation.Reporting.psm1
Labels: bug

#66 chore: update copyright
  LICENSE
  NOTICE
  VMware.CloudFoundation.Reporting.psd1
  VMware.CloudFoundation.Reporting.psm1
Labels: chore

#68 chore(deps): bump `PowerValidatedSolutions` from v1.10.0 to v2.0.0
  README.md
  VMware.CloudFoundation.Reporting.psd1
  VMware.CloudFoundation.Reporting.psm1
Labels: chore, dependencies

#69 docs: update `CHANGELOG.md`
  CHANGELOG.md
Labels: documentation

#75 fix: gh-74
  VMware.CloudFoundation.Reporting.psm1
Labels: bug, report/health

#83 chore(release): prepare release
  CHANGELOG.md
  VMware.CloudFoundation.Reporting.psd1
Labels: chore, needs-review, size/xs

#84 chore(release): prepare release
  README.md
  VMware.CloudFoundation.Reporting.psd1
Labels: chore, size/xs
