Repository vmware/powershell-module-for-vmware-cloud-foundation-reporting, pull requests merged in 2023-02, with the labels that each got.

#85 feat: add cpu cores per socket
  VMware.CloudFoundation.Reporting.psm1
Labels: enhancement, report/overview

#79 feat: update `Publish-*` methods for JSON generation
  VMware.CloudFoundation.Reporting.psm1
Labels: size/m, feature

#86 fix: vrealize product display name
  VMware.CloudFoundation.Reporting.psm1
Labels: bug, report/overview

#87 feat: add vcf+ subscription cores
  VMware.CloudFoundation.Reporting.psm1
Labels: enhancement

#88 docs: update `README.md`
  README.md
Labels: documentation

#93 enhancement: specify encoding for `Out-File`
  VMware.CloudFoundation.Reporting.psm1
Labels: enhancement, size/xs

#94 fix: vcenter server ring topology
  VMware.CloudFoundation.Reporting.psd1
  VMware.CloudFoundation.Reporting.psm1
Labels: bug, size/xs, report/health

#95 fix: update backup message
  VMware.CloudFoundation.Reporting.psm1
Labels: bug, size/xs, report/health

#98 docs: update `README.md`
  README.md
Labels: documentation

#99 chore(release): prepare release
  CHANGELOG.md
  README.md
  VMware.CloudFoundation.Reporting.psd1
  VMware.CloudFoundation.Reporting.psm1
Labels: chore
