Repository vmware/powershell-module-for-vmware-cloud-foundation-reporting, pull requests merged in 2023-06, with the labels that each got.

#148 fix: update `Publish-StorageCapacityHealth` cmdlet
  CHANGELOG.md
  VMware.CloudFoundation.Reporting.psd1
  VMware.CloudFoundation.Reporting.psm1
Labels: needs-review

#150 chore: release preparation
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/pull_request_template.md
  CHANGELOG.md
  LICENSE
  VMware.CloudFoundation.Reporting.psd1
  VMware.CloudFoundation.Reporting.psm1
  docs/community/index.md
  docs/index.md
  docs/snippets/install-module.ps1
  mkdocs.yml
Labels: documentation, chore

#152 chore(gh): fix bug issue form
  .github/ISSUE_TEMPLATE/bug.yml
Labels: chore
