Repository vmware/powershell-module-for-vmware-cloud-foundation-reporting, pull requests merged in 2023-05, with the labels that each got.

#131 refactor: isolated workload domains
  CHANGELOG.md
  VMware.CloudFoundation.Reporting.psd1
  VMware.CloudFoundation.Reporting.psm1
Labels: refactor, report/health

#132 feat: add ping connectivity
  CHANGELOG.md
  VMware.CloudFoundation.Reporting.psd1
  VMware.CloudFoundation.Reporting.psm1
Labels: enhancement

#133 fix: update `Request-NetworkOverview`
  VMware.CloudFoundation.Reporting.psd1
  VMware.CloudFoundation.Reporting.psm1
Labels: bug, report/overview

#134 fix: update `Publish-NsxtTier0BgpStatus`
  CHANGELOG.md
  VMware.CloudFoundation.Reporting.psd1
  VMware.CloudFoundation.Reporting.psm1
Labels: bug, report/health

#135 chore: update nsx product terms
  CHANGELOG.md
  VMware.CloudFoundation.Reporting.psd1
  VMware.CloudFoundation.Reporting.psm1
Labels: technical-debt, chore

#136 chore: update example credentials
  VMware.CloudFoundation.Reporting.psd1
  VMware.CloudFoundation.Reporting.psm1
Labels: chore

#137 chore: code formatting
  VMware.CloudFoundation.Reporting.psd1
  VMware.CloudFoundation.Reporting.psm1
Labels: chore

#139 fix: remove sos elements based on version
  CHANGELOG.md
  VMware.CloudFoundation.Reporting.psd1
  VMware.CloudFoundation.Reporting.psm1
Labels: bug

#143 chore: release updates
  CHANGELOG.md
  README.md
  VMware.CloudFoundation.Reporting.psd1
Labels: chore
