Repository vmware/powershell-module-for-vmware-cloud-foundation-reporting, pull requests merged in 2023-10, with the labels that each got.

#179 chore(ci): update actions
  .github/workflows/deploy.yml
  .github/workflows/docs.yml
  .github/workflows/release.yml
Labels: cla-not-required, chore

#180 chore(ci): update tests
  .github/workflows/tests.yml
Labels: cla-not-required, chore

#182 fix: address path related issues
  CHANGELOG.md
  VMware.CloudFoundation.Reporting.psd1
  VMware.CloudFoundation.Reporting.psm1
Labels: bug

#184 docs: update support
  README.md
  docs/community/index.md
  docs/community/support.md
Labels: documentation
