Repository vmware/powershell-module-for-vmware-cloud-foundation-reporting, pull requests merged in 2024-07, with the labels that each got.

#222 feat: add support for vcf-5.2
  CHANGELOG.md
  VMware.CloudFoundation.Reporting.psd1
  VMware.CloudFoundation.Reporting.psm1
  docs/index.md
  mkdocs.yml
Labels: documentation, enhancement, needs-review

#226 chore(deps): update dependencies
  CHANGELOG.md
  VMware.CloudFoundation.Reporting.psd1
  docs/index.md
  docs/install.md
  docs/snippets/copy-module-local-windows.ps1
  docs/snippets/install-module.ps1
  docs/snippets/save-module-local-windows.ps1
Labels: documentation, chore, needs-review, dependencies

#227 chore(release): v2.6.3
  CHANGELOG.md
  VMware.CloudFoundation.Reporting.psd1
Labels: documentation, chore, needs-review
