Repository vmware/powershell-module-for-vmware-cloud-foundation-reporting, pull requests merged in 2025-04, with the labels that each got.

#241 chore(deps): update dependencies
  CHANGELOG.md
  VMware.CloudFoundation.Reporting.psd1
  docs/community/index.md
  docs/community/support.md
  docs/index.md
  docs/snippets/install-module.ps1
Labels: documentation, chore, needs-review, dependencies

#240 chore: update readme
  README.md
Labels: documentation, chore, needs-review

#239 chore(gh): update workflows
  .github/workflows/docs.yml
  .github/workflows/issues.yml
  .github/workflows/lock-threads.yml
  .github/workflows/pull-requests.yml
  .github/workflows/release.yml
  .github/workflows/stale.yml
  .github/workflows/tests.yml
Labels: chore, needs-review, github-actions

#238 chore(gh): update dependabot
  .github/dependabot.yml
Labels: chore, needs-review

#236 chore: update license
  LICENSE
  NOTICE
Labels: chore, needs-review

#235 chore: update contributing
  CONTRIBUTING.md
Labels: documentation, chore, needs-review

#234 chore: update coc
  CODE_OF_CONDUCT.md
Labels: documentation, chore, needs-review

#242 docs: sanitize examples
  docs/documentation/functions/Copy-FiletoSddc.md
Labels: documentation

#245 docs: sanitize examples
  docs/documentation/functions/Invoke-VcfHealthReport.md
  docs/documentation/functions/Invoke-VcfUpgradePrecheck.md
  docs/documentation/functions/Publish-BackupStatus.md
  docs/documentation/functions/Publish-CertificateHealth.md
  docs/documentation/functions/Publish-ClusterConfiguration.md
  docs/documentation/functions/Publish-ClusterDrsRule.md
Labels: documentation, needs-review

#247 docs: sanitize examples
  docs/documentation/functions/Publish-CertificateHealth.md
  docs/documentation/functions/Publish-ComponentConnectivityHealth.md
  docs/documentation/functions/Publish-ComponentConnectivityHealthNonSOS.md
  docs/documentation/functions/Publish-ConnectivityHealth.md
  docs/documentation/functions/Publish-DnsHealth.md
  docs/documentation/functions/Publish-EsxiAlert.md
  docs/documentation/functions/Publish-EsxiConnectionHealth.md
Labels: documentation, needs-review
